sudo: required

services:
  - docker

before_install:
  - docker build -t ggextra-image .

script:
  - rm -rf ggExtra.Rcheck
  - travis_wait 40 docker run -v `pwd`/ggExtra.Rcheck:/home/ggExtra/ggExtra.Rcheck ggextra-image /bin/bash -c 'R CMD build ../ggExtra && R CMD check ggExtra_* --as-cran --no-manual'
